INSERT INTO USERS (NAME) VALUES ('Tim Daller');
INSERT INTO USERS (NAME) VALUES ('Ben Zeh');
INSERT INTO USERS (NAME) VALUES ('Bob Floh');
INSERT INTO USERS (NAME) VALUES ('Margo Mueller');
INSERT INTO USERS (NAME) VALUES ('Evelina Po');
INSERT INTO USERS (NAME) VALUES ('Roy');
INSERT INTO USERS (NAME) VALUES ('Pet Addams');
INSERT INTO USERS (NAME) VALUES ('Katharina Soll');
INSERT INTO USERS (NAME) VALUES ('Derek Johnson');
INSERT INTO USERS (NAME) VALUES ('Emma Thompson');
INSERT INTO USERS (NAME) VALUES ('Oliver Stone');
INSERT INTO USERS (NAME) VALUES ('Sophie Miller');
INSERT INTO USERS (NAME) VALUES ('Henry Ward');
INSERT INTO USERS (NAME) VALUES ('Luna Evans');
INSERT INTO USERS (NAME) VALUES ('Maxwell Black');
INSERT INTO USERS (NAME) VALUES ('Aria White');
INSERT INTO USERS (NAME) VALUES ('Lucas Garcia');
INSERT INTO USERS (NAME) VALUES ('Isabella Brown');
INSERT INTO USERS (NAME) VALUES ('Noah Robinson');
INSERT INTO USERS (NAME) VALUES ('Ava Scott');
INSERT INTO USERS (NAME) VALUES ('Logan Martinez');
INSERT INTO USERS (NAME) VALUES ('Chloe Harris');
INSERT INTO USERS (NAME) VALUES ('Ethan Bell');
INSERT INTO USERS (NAME) VALUES ('Mia Mitchell');
INSERT INTO USERS (NAME) VALUES ('Liam Carter');

INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Echoes of Silence', 'Christopher Adams', 'https://example.com/echoes_silence.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Whispers of Destiny', 'Madison Harris', 'https://example.com/whispers_destiny.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Enigma of Shadows', 'Jack Robinson', 'https://example.com/enigma_shadows.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Realm of Illusions', 'Amelia White', 'https://example.com/realm_illusions.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Legends of Tomorrow', 'Samuel Evans', 'https://example.com/legends_tomorrow.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Chronicles of Fate', 'Harper Carter', 'https://example.com/chronicles_fate.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('The Forgotten Odyssey', 'Logan Bennett', 'https://example.com/forgotten_odyssey.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Songs of the Soul', 'Hannah Foster', 'https://example.com/songs_soul.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Whispers in Time', 'Dylan Kelly', 'https://example.com/whispers_time.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Echoes of Dreams', 'Riley Hayes', 'https://example.com/echoes_dreams.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Journey to Eternity', 'Aria Mitchell', 'https://example.com/journey_eternity.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Melodies of Hope', 'Aaron Stewart', 'https://example.com/melodies_hope.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Tales of Tomorrow', 'Samantha Ward', 'https://example.com/tales_tomorrow.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Whispers in the Dark', 'Elijah Torres', 'https://example.com/whispers_dark.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Echoes of Wisdom', 'Scarlett Gray', 'https://example.com/echoes_wisdom.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Realm of Legends', 'Gabriel Bell', 'https://example.com/realm_legends.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Dreams of Reality', 'Ellie Cooper', 'https://example.com/dreams_reality.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Whispers of Serenity', 'Isaac Price', 'https://example.com/whispers_serenity.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Echoes of Imagination', 'Mia Hughes', 'https://example.com/echoes_imagination.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Journey to Redemption', 'Lucy Martinez', 'https://example.com/journey_redemption.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Melodies of Tranquility', 'Jordan Gonzales', 'https://example.com/melodies_tranquility.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Whispers of Solitude', 'Owen Long', 'https://example.com/whispers_solitude.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Echoes of Reflection', 'Aurora Wood', 'https://example.com/echoes_reflection.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Dreams of Tomorrow', 'Aiden Nelson', 'https://example.com/dreams_tomorrow.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Whispers of the Heart', 'Stella Ramirez', 'https://example.com/whispers_heart.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Melodies of Inspiration', 'Wyatt Butler', 'https://example.com/melodies_inspiration.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Echoes of Change', 'Nova Fisher', 'https://example.com/echoes_change.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Journey to Harmony', 'Julia Ward', 'https://example.com/journey_harmony.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Melodies of Adventure', 'Mason Cox', 'https://example.com/melodies_adventure.mp3');
INSERT INTO AUDIOBOOK (AUDIOBOOK_TITLE,AUDIOBOOK_AUTHOR,AUDIO_URL) VALUES ('Whispers of Fantasy', 'Eva Price', 'https://example.com/whispers_fantasy.mp3');

INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES(1, 1, 120);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES(2, 2, 150);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES(3, 3, 180);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES(4, 4, 200);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES(5, 5, 220);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES(6, 6, 250);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES(7, 7, 270);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES(8, 8, 300);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES        (9, 9, 320);
INSERT INTO BOOKMARK (AUDIBOOK_ID, USER_ID, LASTPLAYED_TIME) VALUES        (10, 10, 350);