CREATE TABLE AUDIOBOOK
(
    AUDIOBOOK_ID     BIGSERIAL PRIMARY KEY,
    AUDIOBOOK_TITLE  VARCHAR(255),
    AUDIOBOOK_AUTHOR VARCHAR(255),
    AUDIO_URL        VARCHAR(255)

);



CREATE TABLE USERS
(
    USER_ID BIGSERIAL PRIMARY KEY,
    NAME    VARCHAR(255)
);



CREATE TABLE BOOKMARK
(
    BOOKMARK_ID     BIGSERIAL PRIMARY KEY,
    AUDIBOOK_ID     BIGINT,
    USER_ID         BIGINT,
    LASTPLAYED_TIME INT,
    FOREIGN KEY (AUDIBOOK_ID) REFERENCES AUDIOBOOK (AUDIOBOOK_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

