CREATE TABLE AUDIOBOOK
(
    AUDIOBOOK_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIOBOOK_TITLE  VARCHAR(255),
    AUDIOBOOK_AUTHOR VARCHAR(255),
    AUDIO_URL        VARCHAR(255)

);
CREATE TABLE USER
(
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(255)
);

CREATE TABLE BOOKMARK
(
    BOOKMARK_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIBOOK_ID     BIGINT,
    USER_ID         BIGINT,
    LASTPLAYED_TIME INT,
    FOREIGN KEY (AUDIBOOK_ID) REFERENCES AUDIOBOOK (AUDIOBOOK_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

